// <auto-generated />
using System;
using DeliveryPlatform.Persistence.EFCore.DeliveryPlatformDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryPlatform.Persistence.EFCore.DeliveryPlatformDb.Migrations
{
    [DbContext(typeof(DeliveryPlatformDbContext))]
    [Migration("20260218160220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deliveryplatform")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Deliveries.Models.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Load")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PickupNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PickupNodeId");

                    b.HasIndex("Status", "ServiceDate");

                    b.ToTable("Deliveries", "deliveryplatform");
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Drivers.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Drivers", "deliveryplatform");
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Nodes.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Nodes", "deliveryplatform");
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Routes.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Routes", "deliveryplatform");
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Routes.Models.RouteSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("TravelTimeMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("RouteId", "Order");

                    b.ToTable("RouteSegments", "deliveryplatform");
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Vehicles.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("DepotNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SpeedKmh")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepotNodeId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("Vehicles", "deliveryplatform");
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Deliveries.Models.Delivery", b =>
                {
                    b.HasOne("DeliveryPlatform.Core.Domain.Nodes.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryPlatform.Core.Domain.Nodes.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("PickupNodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Routes.Models.Route", b =>
                {
                    b.HasOne("DeliveryPlatform.Core.Domain.Drivers.Models.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryPlatform.Core.Domain.Vehicles.Models.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Routes.Models.RouteSegment", b =>
                {
                    b.HasOne("DeliveryPlatform.Core.Domain.Deliveries.Models.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryPlatform.Core.Domain.Routes.Models.Route", null)
                        .WithMany("Segments")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Vehicles.Models.Vehicle", b =>
                {
                    b.HasOne("DeliveryPlatform.Core.Domain.Nodes.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("DepotNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryPlatform.Core.Domain.Routes.Models.Route", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
